[package]
authors = ["Alan C <digikata@gmail.com>"]
name = "picshuffle"
version = "0.1.7"
edition = "2018"

[dependencies]
chrono = "0.4.*"
clap = "2.*"
ignore = "0.2.*"
rust-crypto = "0.2.*"
kamadak-exif = "0.3.*"
